INSERT INTO TBL_CITY(NAME, STATE, POPULATION, PIB) VALUES('Salto', 'Sao Paulo', '200000', '2');
INSERT INTO TBL_CITY(NAME, STATE, POPULATION, PIB) VALUES('Itu', 'Sao Paulo', '260000', '3');
INSERT INTO TBL_CITY(NAME, STATE, POPULATION, PIB) VALUES('Indaiatuba', 'Sao Paulo', '300000', '4');
